/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.senac.pifindajob.telas;


import br.com.senac.pifindajob.classes.Candidato;
import br.com.senac.pifindajob.persistencia.BuscarPorCursoDao;
import br.com.senac.pifindajob.persistencia.CandidatoDao;
import java.util.List;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Rosilane
 */
public class BuscarCandidato extends javax.swing.JFrame{
    
    public void preencheTabela(List<Candidato> candidatos) {
        String colunas[] = {"Nome", "Curso", "Instituição"};
        String dados[][] = new String[candidatos.size()][colunas.length];

        int i = 0;
        for (Candidato c : candidatos) {
            String curso = "N/A"; 
            String instituicao = "N/A";

            if (c.getFormacaoAcademica() != null) {
                curso = c.getFormacaoAcademica().getCurso();
                instituicao = c.getFormacaoAcademica().getInstituicao();
            }
            dados[i] = new String[]{
            c.getNome(),
            curso,
            instituicao
            };
            i++;
        }
        
        DefaultTableModel model = new DefaultTableModel(dados, colunas);
        tblResultados.setModel(model);
        System.out.println("Total de candidatos encontrados: " + candidatos.size());
    }
    
    public BuscarCandidato() {
      initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPTitulo = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        jPOpcoes = new javax.swing.JPanel();
        btnBuscarCandidatos = new javax.swing.JButton();
        btnAnalisarCandidatos = new javax.swing.JButton();
        btnGerenciarVagas = new javax.swing.JButton();
        btnAgendarEntrevistas = new javax.swing.JButton();
        btnconfiguracoes = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lblEncontre = new javax.swing.JLabel();
        txtPesquisa = new javax.swing.JTextField();
        jPAreaResultado = new javax.swing.JPanel();
        checkTecnologia = new javax.swing.JCheckBox();
        checkAdministracao = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblResultados = new javax.swing.JTable();

        jPTitulo.setBackground(new java.awt.Color(255, 255, 255));

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitulo.setText("Find a Job");

        javax.swing.GroupLayout jPTituloLayout = new javax.swing.GroupLayout(jPTitulo);
        jPTitulo.setLayout(jPTituloLayout);
        jPTituloLayout.setHorizontalGroup(
            jPTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPTituloLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addGap(312, 312, 312))
        );
        jPTituloLayout.setVerticalGroup(
            jPTituloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPTituloLayout.createSequentialGroup()
                .addComponent(lblTitulo)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        jPOpcoes.setBackground(new java.awt.Color(100, 181, 246));

        btnBuscarCandidatos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnBuscarCandidatos.setText("Buscar Candidatos");
        btnBuscarCandidatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCandidatosActionPerformed(evt);
            }
        });

        btnAnalisarCandidatos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAnalisarCandidatos.setText("Analisar Candidatos");
        btnAnalisarCandidatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalisarCandidatosActionPerformed(evt);
            }
        });

        btnGerenciarVagas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnGerenciarVagas.setText("Gerenciar Vagas");
        btnGerenciarVagas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerenciarVagasActionPerformed(evt);
            }
        });

        btnAgendarEntrevistas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAgendarEntrevistas.setText("Agendar Entrevistas");

        btnconfiguracoes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnconfiguracoes.setText("Configurações");

        javax.swing.GroupLayout jPOpcoesLayout = new javax.swing.GroupLayout(jPOpcoes);
        jPOpcoes.setLayout(jPOpcoesLayout);
        jPOpcoesLayout.setHorizontalGroup(
            jPOpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPOpcoesLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPOpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnconfiguracoes, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAnalisarCandidatos, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarCandidatos, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGerenciarVagas, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgendarEntrevistas, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPOpcoesLayout.setVerticalGroup(
            jPOpcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPOpcoesLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btnBuscarCandidatos, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnAnalisarCandidatos, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnGerenciarVagas, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnAgendarEntrevistas, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btnconfiguracoes, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(100, 181, 246));

        lblEncontre.setFont(new java.awt.Font("Segoe UI", 2, 20)); // NOI18N
        lblEncontre.setForeground(new java.awt.Color(255, 255, 255));
        lblEncontre.setText("Encontre um Funcionário pela sua formação:");

        txtPesquisa.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtPesquisaCaretUpdate(evt);
            }
        });

        jPAreaResultado.setBackground(new java.awt.Color(217, 217, 217));

        javax.swing.GroupLayout jPAreaResultadoLayout = new javax.swing.GroupLayout(jPAreaResultado);
        jPAreaResultado.setLayout(jPAreaResultadoLayout);
        jPAreaResultadoLayout.setHorizontalGroup(
            jPAreaResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPAreaResultadoLayout.setVerticalGroup(
            jPAreaResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 374, Short.MAX_VALUE)
        );

        checkTecnologia.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        checkTecnologia.setText("Tecnologia");

        checkAdministracao.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        checkAdministracao.setText("Administração");

        tblResultados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Nome", "Curso", "Instituição"
            }
        ));
        jScrollPane1.setViewportView(tblResultados);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(lblEncontre))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(checkTecnologia)
                        .addGap(39, 39, 39)
                        .addComponent(checkAdministracao))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPAreaResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblEncontre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkTecnologia)
                    .addComponent(checkAdministracao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPAreaResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPOpcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPOpcoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAnalisarCandidatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalisarCandidatosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAnalisarCandidatosActionPerformed

    private void btnBuscarCandidatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCandidatosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarCandidatosActionPerformed

    private void btnGerenciarVagasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerenciarVagasActionPerformed
         GerenciarVagas gerenciar = new GerenciarVagas();
         gerenciar.setVisible(true);
    }//GEN-LAST:event_btnGerenciarVagasActionPerformed

    private void txtPesquisaCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtPesquisaCaretUpdate
        if (txtPesquisa.getText().isEmpty()) {
        }else{
            BuscarPorCursoDao candidatoDao = new BuscarPorCursoDao();
            List<Candidato> candidatos = candidatoDao.listar(txtPesquisa.getText());
            preencheTabela(candidatos);
        }
    }//GEN-LAST:event_txtPesquisaCaretUpdate

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarCandidato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarCandidato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarCandidato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarCandidato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
           new BuscarCandidato().setVisible(true);
 
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgendarEntrevistas;
    private javax.swing.JButton btnAnalisarCandidatos;
    private javax.swing.JButton btnBuscarCandidatos;
    private javax.swing.JButton btnGerenciarVagas;
    private javax.swing.JButton btnconfiguracoes;
    private javax.swing.JCheckBox checkAdministracao;
    private javax.swing.JCheckBox checkTecnologia;
    private javax.swing.JPanel jPAreaResultado;
    private javax.swing.JPanel jPOpcoes;
    private javax.swing.JPanel jPTitulo;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEncontre;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTable tblResultados;
    private javax.swing.JTextField txtPesquisa;
    // End of variables declaration//GEN-END:variables
}
