/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.senac.pifindajob.telas;


import javax.swing.JOptionPane;

/**
 *
 * @author Rosilane
 */
public class TelaCadastro extends javax.swing.JFrame {
 
    /**
     * Creates new form TelaCadastro
     */
    public TelaCadastro() {
        initComponents();
       
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jRadioProcurandoFunc = new javax.swing.JRadioButton();
        jRadioProcurandoEmprego = new javax.swing.JRadioButton();
        btnConfirmarContinuar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0)));

        jRadioProcurandoFunc.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jRadioProcurandoFunc.setText("  Procurando Funcionário");
        jRadioProcurandoFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioProcurandoFuncActionPerformed(evt);
            }
        });

        jRadioProcurandoEmprego.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jRadioProcurandoEmprego.setText("  Procurando Emprego");
        jRadioProcurandoEmprego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioProcurandoEmpregoActionPerformed(evt);
            }
        });

        btnConfirmarContinuar.setBackground(new java.awt.Color(25, 118, 210));
        btnConfirmarContinuar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnConfirmarContinuar.setForeground(new java.awt.Color(255, 255, 255));
        btnConfirmarContinuar.setText("Confirmar e Continuar");
        btnConfirmarContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarContinuarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioProcurandoEmprego)
                    .addComponent(jRadioProcurandoFunc))
                .addGap(159, 159, 159))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(btnConfirmarContinuar, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(132, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jRadioProcurandoFunc)
                .addGap(36, 36, 36)
                .addComponent(jRadioProcurandoEmprego)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addComponent(btnConfirmarContinuar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioProcurandoEmpregoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioProcurandoEmpregoActionPerformed
       /* if (checkProcurandoEmprego()) {

            jRadioProcurandoEmprego.setSelected(true);
            jRadioProcurandoFunc.setSelected(false);
        }*/
    }//GEN-LAST:event_jRadioProcurandoEmpregoActionPerformed

    private void jRadioProcurandoFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioProcurandoFuncActionPerformed
       /* if (checkProcurandoFuncionario()) {

            jRadioProcurandoFunc.setSelected(true);
            jRadioProcurandoEmprego.setSelected(false);
        }*/
    }//GEN-LAST:event_jRadioProcurandoFuncActionPerformed

    private void btnConfirmarContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarContinuarActionPerformed
      
    /*int tipoUsuario = 0;

    if (jRadioProcurandoEmprego.isSelected()) {
        tipoUsuario = 2;
        //CadastroTrabalhador cadastroTrabalhador = new CadastroTrabalhador(findAJob, tipoUsuario); 
       // cadastroTrabalhador.setVisible(true);
        this.dispose();
    } 
    else if (jRadioProcurandoFunc.isSelected()) {
        tipoUsuario = 1;
        //CadastroEmpresa cadastroEmpresa = new CadastroEmpresa(findAJob, tipoUsuario); 
       // cadastroEmpresa.setVisible(true);
        this.dispose();
    } 
    else {
        JOptionPane.showMessageDialog(this, "Por favor, você precisa selecionar uma opção antes de continuar.");
    }*/
    }//GEN-LAST:event_btnConfirmarContinuarActionPerformed

    /**
     * @param args the command line arguments
     */
   public static void main(String args[]) {
    /* Configuração do Look and Feel Nimbus */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException ex) {
        java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
        java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
        java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }

    /* Criação e exibição do formulário */
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
            
            new TelaCadastro().setVisible(true);
        }
    });
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConfirmarContinuar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioProcurandoEmprego;
    private javax.swing.JRadioButton jRadioProcurandoFunc;
    // End of variables declaration//GEN-END:variables


/*private boolean checkProcurandoEmprego() {
        boolean cheked = false;
        if (jRadioProcurandoEmprego.isSelected()) {
            cheked = true;
        }
        return cheked;
    }

    private boolean checkProcurandoFuncionario() {
        boolean cheked = false;
        if (jRadioProcurandoFunc.isSelected()) {
            cheked = true;
        }
        return cheked;
    }*/
}


 

