/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.senac.pifindajob.telas;

import br.com.senac.pifindajob.classes.Candidato;
import br.com.senac.pifindajob.classes.Usuario;
import br.com.senac.pifindajob.persistencia.CandidatoDao;
import br.com.senac.pifindajob.persistencia.UsuarioDao;
import javax.swing.JOptionPane;

/**
 *
 * @author Rosilane
 */
public class TelaCriarConta extends javax.swing.JFrame {

    /**
     * Creates new form TelaCriarConta
     */
    public TelaCriarConta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtSenha = new javax.swing.JTextField();
        btnCriar = new javax.swing.JButton();
        jRadioProcurandoFunc = new javax.swing.JRadioButton();
        jRadioProcurandoEmprego = new javax.swing.JRadioButton();

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Email:");

        txtEmail.setBackground(new java.awt.Color(204, 204, 204));
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Senha:");

        txtSenha.setBackground(new java.awt.Color(204, 204, 204));

        btnCriar.setBackground(new java.awt.Color(255, 102, 102));
        btnCriar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCriar.setForeground(new java.awt.Color(255, 255, 255));
        btnCriar.setText("criar conta");
        btnCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarActionPerformed(evt);
            }
        });

        jRadioProcurandoFunc.setText("  Procurando Funcionário");
        jRadioProcurandoFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioProcurandoFuncActionPerformed(evt);
            }
        });

        jRadioProcurandoEmprego.setText("  Procurando Emprego");
        jRadioProcurandoEmprego.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioProcurandoEmpregoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addComponent(btnCriar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioProcurandoFunc)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addGap(32, 32, 32)
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addGap(29, 29, 29)
                                    .addComponent(txtSenha)))
                            .addComponent(jRadioProcurandoEmprego))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addComponent(jRadioProcurandoFunc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jRadioProcurandoEmprego)
                .addGap(26, 26, 26)
                .addComponent(btnCriar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void btnCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarActionPerformed
        Usuario user = new Usuario();
            UsuarioDao dao = new UsuarioDao();
        if(validaCampos() == false){
            JOptionPane.showMessageDialog(rootPane, "Por favor, preencha todos os campos obrigatórios!");
        }else if(campoSelecionado()== false){
            JOptionPane.showMessageDialog(this, "Por favor, você precisa selecionar uma opção antes de continuar.");
            
        }else{
            if(dao.verificarSeUserCadastrado(txtEmail.getText())){
             
                 JOptionPane.showMessageDialog(this, "Usuário já cadastrado!");
                
            }else{
                 user.setEmail(txtEmail.getText());
                 user.setSenha(txtSenha.getText());
                 user.setTipo_usuario(getTipoUser());
            
                dao.cadastrar(user);
            
                JOptionPane.showMessageDialog(rootPane, "Usuario cadastrado com sucesso!");
                limparCampos(); 
            }
        }  
       
    }//GEN-LAST:event_btnCriarActionPerformed

    private void jRadioProcurandoFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioProcurandoFuncActionPerformed
        // TODO add your handling code here:
        if (checkProcurandoFuncionario()) {

            jRadioProcurandoFunc.setSelected(true);
            jRadioProcurandoEmprego.setSelected(false);
        }
    }//GEN-LAST:event_jRadioProcurandoFuncActionPerformed

    private void jRadioProcurandoEmpregoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioProcurandoEmpregoActionPerformed
        // TODO add your handling code here:
        if (checkProcurandoEmprego()) {

            jRadioProcurandoEmprego.setSelected(true);
            jRadioProcurandoFunc.setSelected(false);
        }
    }//GEN-LAST:event_jRadioProcurandoEmpregoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCriarConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCriarConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCriarConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCriarConta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCriarConta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCriar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioProcurandoEmprego;
    private javax.swing.JRadioButton jRadioProcurandoFunc;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtSenha;
    // End of variables declaration//GEN-END:variables

    private boolean validaCampos(){
     if(txtEmail.getText().isEmpty()){
        JOptionPane.showMessageDialog(rootPane,"Campo email não pode ser vazio" );
        return false;
    }else if(txtSenha.getText().isEmpty()){
         JOptionPane.showMessageDialog(rootPane,"Campo senha não pode ser vazio" );
         return false;
    } else {
        return true;
    }
}
    public void limparCampos() {

            txtEmail.setText("");
            txtSenha.setText("");

    }

    private boolean checkProcurandoEmprego() {
            boolean cheked = false;
            if (jRadioProcurandoEmprego.isSelected()) {
                cheked = true;
            }
            return cheked;
        }

    private boolean checkProcurandoFuncionario() {
        boolean cheked = false;
        if (jRadioProcurandoFunc.isSelected()) {
            cheked = true;
        }
        return cheked;
    }

    
    private boolean campoSelecionado(){
        int tipoUsuario = 0;
        boolean selecionado = false;
        if (jRadioProcurandoEmprego.isSelected()) {
            selecionado = true;
            tipoUsuario = 2;
            this.dispose();
        }else if (jRadioProcurandoFunc.isSelected()) {
            tipoUsuario = 1;
            this.dispose();
            selecionado = true;
        } 
            return selecionado;
    }
    
    private int getTipoUser(){
        int tipoUser=0;
        if (jRadioProcurandoEmprego.isSelected()) {
           tipoUser = 2;
        }else if (jRadioProcurandoFunc.isSelected()) {
           tipoUser = 1;
        } 
        return tipoUser;
    }
}
